# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f720a6c808657846b9483174b216f2d99ea6729b552f799fccc258ade13efbc5368edb81945fe1fa285e09cae111d1f99d0ae23b4ff3d9ec659f0035b8d444e0

test:
  secret_key_base: 5fa0636ca0f0ec56b06d7fdae198e4e369d6781291ddc8fc0e61e608e85c13364bdfd78c8678eaa685c9c8179e4efb4cc92df4367bc806c6a7a2c3e82b75b6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
